### ISSUE TITLE
Matching footprints

### ISSUE THREAD

**Issue by HendriXML** [HendriXML/KiCad-BOM-reporter#16]
I'd like to improve the matching of schema components and stock components taking the footprint into account.
At the moment there're config files that map symbol components to component kinds (resistors/capacitors, etc).
I think there should also be config files that map footprints to a "footprint kind".
Because footprints can be managed by PartKeepr a static list may not fill the bill. (At this moment it is a static "list" (enumeration) in the script, which is very limited).
However if a static list used industry standard identifiers (pdip-8 for instance), which could also be implemented entirely by PartKeepr this would be no issue.
But for THT this might be a bit tricky. Not all component kinds might have to be matched by footprint though. Having a footprint technology type (SMT/THT) might be discriminating enough. (In a way that is how It's implemented now).
Also the list can be partly static and dynamic. (Use of a other.. category).

I would like to know for whom this would be an important feature.

**Comment by HendriXML** [comment]
I've done some more research on footprints, which may give a bit more direction to a solution.

First: the number of standard footprints on GitHub is 9730.

Identifying them is undoable. Extracting a usable identifier is not trivial. The free format data in the description or the name needs to be analysed for that. So the implementation can only be limited for those components / footprints for which it has the greatest benefits. Offering the user the possibility to add mapping configurations them selves.

I think capacitors, resistors, inductors, diodes, ic's, transistors are likely to be manufactured with same specs, but in different packaging and actually end up on the shelves in the e-lab. For other components more strict matching can be forced with other criteria.

One component can often be used for several footprints. Resistors for instance can be standing, or horizontal and be spread narrow or wide. From a PartKeeper's perspective PackageType  would be a better name. I will use that terminology for now on.

A PackageType can be matched with one or more foot prints.

The implementation will also extract this package type from a components parameters. This because this data is more flexible (value does not need to be in a list). And it can also be defined on the category level, the same way as other parameters.

Why does it need to be flexible?
I'm thinking about identifiers that contain attribute data that can be extracted. For instance a normal resistor with leads can bridge a certain length. Also it has a certain width. Those attribute can be used to match footprints with. This reduces the number of (static parts of) identifiers.
For instance PDIP-8, PDIP-14, PDIP-16, etc the static part will be PDIP, the dynamic part will be the pin count.
For SMT and THT resistors the attributes to match on are different. So it is better that the static part between them is different. Also the same package type could be (re)used by different component classes, what's in the package is stated in the componentkind. For a KiCad footprint this is a bit different, because there's a difference in the graphical display of different component classes.
Footprints in KiCad will be mapped to data/attributes that can be used to match package types. This data will be read from config files.

**Comment by Gasman2014** [comment]
Can you not use the IPC7351 convention? http://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/IPC-7x51%20&%20PCBM%20Land%20Pattern%20Naming%20Convention.pdf

**Comment by HendriXML** [comment]
Thank you for the reference, it shows what a naming convention could look like, with the opportunity to extract relevant parameters from it.

The way I see thing now is that stock components get a package-type identifier, which contains the right amount of information to match KiCad footprints with them.

A (maintenance) task will match these identifiers with the supplied footprints of KiCad. This will generate a file which contain for each identifiers all the matching KiCad footprints. This way the matching footprints can also be shown as extra information on each component. 

For components that could not automatically be matched the same kind of file can be added manually.

In this case the package identifiers should also include component kind info. So the reference you gave for land patterns seems very useful. I have to examine how it relates to the information that can be extracted from KiCad's footprints. Also for THT things might be a bit different.

**Comment by HendriXML** [comment]
Having wrestled with this for a while, the solution took another direction.
Instead of using identifiers, which need to be interpreted - which needs a lot of logic. The solution will use "mask matching" the KiCad footprint "identifiers".

For instance my low power resistors can match the KiCad footprints with this expression:
Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P((2.54|5.08)mm_Vertical|(7.62|10.16|15.24)mm_Horizontal)
Using nested text alternates this allows to match witch 5 different footprints. Without the string becoming too long.
It also could be expressed as:
Resistor_THT:R_Axial_DIN0207_*
Allowing for more footprints to match.
 
![Footprints](https://user-images.githubusercontent.com/40315442/66261547-a1c80e80-e7cf-11e9-8ff2-654318b2d09e.png)
